name: "cyan-builder"

on:
  push:
    branches:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"
      - uses: leafo/gh-actions-luarocks@v4

      - name: Install the cyan build system for Teal
        run: luarocks install cyan

      - name: Create luarocks archive
        run: |
          zip -r luarocks.zip ${GITHUB_WORKSPACE}/.luarocks

      - name: Dump workspace tree
        run: |
          tree -a ${GITHUB_WORKSPACE}

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: linux-cyan
          path: luarocks.zip
