name: "cyan-builder"

on:
  push:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [linux-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"
      - uses: hishamhm/gh-actions-luarocks

      - name: Install the cyan build system for Teal
        run: luarocks install cyan

      - name: Dump workspace tree
        run: |
          tree -a ${GITHUB_WORKSPACE}

      - name: Create luarocks archive
        run: |
          zip -r luarocks.zip ${GITHUB_WORKSPACE}/.luarocks

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: ${RUNNER_OS}-cyan
          path: luarocks.zip
