name: "cyan-builder"

on:
  push:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [linux-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@master
        with:
          luaVersion: "luajit"
      - uses: hishamhm/gh-actions-luarocks@master

      - name: Install the cyan build system for Teal
        shell: cmd
        run: luarocks install cyan

      - uses: vimtor/action-zip@v1.2
        with:
          files: ${GITHUB_WORKSPACE}/.luarocks/
          dest: luarocks.zip

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: ${RUNNER_OS}-cyan
          path: luarocks.zip
