name: "cyan-builder"

on:
  push:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: leafo/gh-actions-lua@master
        with:
          luaVersion: "5.1.5"
      - uses: hishamhm/gh-actions-luarocks@5013277f6f115c27478f18c1f647f8de98390628

      - name: Install the cyan build system for Teal
        shell: cmd
        run: luarocks install cyan

      - name: Create luarocks archive
        run: |
          zip -r luarocks.zip ${GITHUB_WORKSPACE}/.luarocks

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: ${RUNNER_OS}-cyan
          path: luarocks.zip
